main: com.github.bane34.main.SimplePlugin
version: 1.0.1
name: SimplePlugin

commands:
  simpleplugin:
    description: main command of the plugin
  strikelightning:
    description: strikes a lightning in a player